### ISSUE TITLE
Request: Voucher Code

### ISSUE THREAD

**Issue by strigona-worksight** [kobaltz/pfsense_captive_portal#1]
Might be nice to supply a couple different versions of login.html with the different combinations of voucher code/login.

1: Login only
2: Voucher only
3: Login & Voucher

**Comment by kobaltz** [comment]
Would be very easy since `auth_user` can be replaced with `auth_voucher` and the password div removed. I'll add a few extras tonight once the kiddos are to bed.

**Comment by strigona-worksight** [comment]
Yeah, I figured it was trivial and don't really need it for myself, but I know the standard captive portal has all 3 fields.

Overall it looks very nice.. will be installing it at home later.

**Comment by kobaltz** [comment]
I've updated the repo quite a bit and added another theme. Enjoy!
